#!/usr/bin/env python3
"""Session checkpoint: writes sessionState.md with git state.

Triggered by the Stop hook event after every Claude response.
Writes atomically (temp file + rename) to prevent corruption on crash.
No-op if not in a git repository.
"""

import json
import os
import subprocess
import sys
import tempfile
from datetime import datetime, timezone


def is_git_repo(cwd: str) -> bool:
    """Return True if cwd is inside a git working tree."""
    try:
        result = subprocess.run(
            ['git', 'rev-parse', '--is-inside-work-tree'],
            capture_output=True, text=True, cwd=cwd, timeout=3
        )
        return result.returncode == 0 and result.stdout.strip() == 'true'
    except Exception:
        return False


def run_git(args: list[str], cwd: str) -> str:
    """Run a git command and return stdout, or empty string on failure."""
    try:
        result = subprocess.run(
            ['git'] + args,
            capture_output=True, text=True, cwd=cwd, timeout=3
        )
        return result.stdout.strip() if result.returncode == 0 else ''
    except Exception:
        return ''


def get_git_state(cwd: str) -> dict:
    """Collect git state from the working directory."""
    branch = run_git(['rev-parse', '--abbrev-ref', 'HEAD'], cwd)
    commits = run_git(['log', '--oneline', '-3'], cwd)

    # Count staged files
    staged_output = run_git(['diff', '--cached', '--name-only'], cwd)
    staged_count = len([f for f in staged_output.splitlines() if f.strip()]) if staged_output else 0

    # Count unstaged files
    unstaged_output = run_git(['diff', '--name-only'], cwd)
    unstaged_count = len([f for f in unstaged_output.splitlines() if f.strip()]) if unstaged_output else 0

    # Count untracked files
    untracked_output = run_git(['ls-files', '--others', '--exclude-standard'], cwd)
    untracked_count = len([f for f in untracked_output.splitlines() if f.strip()]) if untracked_output else 0

    return {
        'branch': branch,
        'commits': commits,
        'staged': staged_count,
        'unstaged': unstaged_count,
        'untracked': untracked_count,
    }


def format_session_state(state: dict, session_id: str, last_action: str) -> str:
    """Format git state as a markdown document."""
    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')

    lines = [
        '# Session State — Auto-Checkpoint',
        '',
        f'_Auto-generated by Stop hook. Last updated: {now}_',
        f'_Session ID: {session_id}_',
        '',
        '## Git State',
        '',
        f'- **Branch**: `{state["branch"]}`',
        f'- **Staged files**: {state["staged"]}',
        f'- **Unstaged files**: {state["unstaged"]}',
        f'- **Untracked files**: {state["untracked"]}',
        '',
    ]

    if state['staged'] > 0 or state['unstaged'] > 0:
        lines.append(f'> WARNING: {state["staged"]} staged, {state["unstaged"]} unstaged files exist. Recovery requires checking `git diff` and `git status`.')
        lines.append('')

    lines.extend([
        '### Last 3 Commits',
        '',
        '```',
        state['commits'] if state['commits'] else '(no commits)',
        '```',
        '',
        '## Last Claude Action',
        '',
        '```',
        last_action if last_action else '(unknown)',
        '```',
        '',
        '## Recovery Instructions',
        '',
        'If this session crashed or was interrupted, start here:',
        '',
        '  1. Run `git log --oneline -5` — last known commits above',
        '  2. Run `git status` — check for uncommitted work',
        '  2b. Run `git stash list` — check for stashed work',
        '  3. Run `git diff` — review uncommitted changes',
        '  4. Read `.claude/retrospective-log.md` — last recorded events',
        '  5. Read `python/voicetrainer/pipeline_runner.py` — current pipeline state',
        '',
        '## Notes',
        '',
        '_Add manual notes below this line for context that automated recovery cannot capture._',
        '',
        '---',
        '',
    ])

    return '\n'.join(lines)


def atomic_write(path: str, content: str) -> None:
    """Write content to path atomically via temp file + rename."""
    dir_path = os.path.dirname(path)
    fd, tmp_path = tempfile.mkstemp(dir=dir_path, suffix='.tmp', prefix='.sessionState_')
    try:
        os.write(fd, content.encode('utf-8'))
        os.close(fd)
        os.replace(tmp_path, path)
    except Exception:
        os.close(fd) if not os.get_inheritable(fd) else None
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise


def main():
    try:
        # Read hook input from stdin
        input_data = json.loads(sys.stdin.read())
        cwd = input_data.get('cwd', '')
        session_id = input_data.get('session_id', 'unknown')
        last_message = input_data.get('last_assistant_message', '')

        # Truncate last message to first line for brevity
        last_action = last_message.split('\n')[0][:200] if last_message else ''

        if not cwd or not is_git_repo(cwd):
            # Not a git repo — no-op
            print(json.dumps({"hookSpecificOutput": {"hookEventName": "Stop", "skipped": True}}))
            return

        state = get_git_state(cwd)
        content = format_session_state(state, session_id, last_action)

        target = os.path.join(cwd, 'sessionState.md')
        atomic_write(target, content)

        print(json.dumps({"hookSpecificOutput": {"hookEventName": "Stop", "wrote": target}}))

    except Exception:
        # Never break the system — swallow all errors
        print(json.dumps({"hookSpecificOutput": {"hookEventName": "Stop", "error": True}}))


if __name__ == '__main__':
    main()
